version: '3'

services:
  django:
    build:
      context: .
    container_name: django
    image: rzmobiledev/django:1.0.0
    # command: >
    #   sh -c "python manage.py wait_for_db &&
    #   python manage.py migrate &&
    #   python manage.py runserver 0.0.0.0:8000"
    ports:
      - 80:8000
    volumes:
      - ./app:/app
      - ./data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=1
      - SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - db

  
  db:
    image: postgres:alpine3.15
    volumes:
      - postgres-data:/vol/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432


volumes:
  data:
  postgres-data: