apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
    app: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: rzmobiledev/django:1.0.0 #<---change with your dockerhub account
        ports:
        - containerPort: 8000
          name: gunicorn