apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django-app
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000